### ISSUE TITLE
Baseline Implementations

### ISSUE THREAD

**Issue by AvantiB** [tqzhong/CG4MCTG#1]
Hi,

Great paper and congratulations on getting accepted to ACL 2024!! 
I was wondering if you could please provide the implementations of the baselines used in the paper (Appendix D.1). This would make the repository truly comprehensive and a one-stop solution for recent controllable text generation methods.
Thanks.

Best,
Avanti

**Comment by tqzhong** [comment]
Thank you for your suggestion! We will make adjustments to the repository and enhance the baseline codes in subsequent updates in the near future. Please stay tuned.

**Comment by AvantiB** [comment]
Thanks.. Just to clarify, the code provided in this repository is for the **DCG** (Zeng et al., Seen to Unseen: Exploring Compositional Generalization of Multi-Attribute Controllable Dialogue Generation) baseline. correct?

**Comment by tqzhong** [comment]
Yes, currently, there is only the code of DCG

**Comment by Zhaoyi-Li21** [comment]
Hi, Avanti.

Recently we have released the codes of CTRL and CatPrefix.
