### ISSUE TITLE
Evaluation Models

### ISSUE THREAD

**Issue by HectorAuvinen** [tqzhong/CG4MCTG#2]
Hello,

Could you share the evaluation models through Google Drive? I am having issues accessing the models through the current platform. Thank you!

Kind regards,
Hector

**Comment by Zhaoyi-Li21** [comment]
> Hello,
> 
> Could you share the evaluation models through Google Drive? I am having issues accessing the models through the current platform. Thank you!
> 
> Kind regards, Hector

Hi, Hector.

Thanks for bringing the issue into our attention! We are now seeking a way to share the evaluation models (through google drive, huggingface or something). Due to the large size of these models, it may cost some time. We will manage it asap and let you know then.

Zhaoyi

**Comment by tqzhong** [comment]
> Hello,
> 
> Could you share the evaluation models through Google Drive? I am having issues accessing the models through the current platform. Thank you!
> 
> Kind regards, Hector

Hi, Hector

Thanks for your attention and we have made a new link to these evaluation models.

**Comment by Zhaoyi-Li21** [comment]
Hey, @HectorAuvinen. Please feel free to reopen the issue should here has remaining question.
