### ISSUE TITLE
Missing module

### ISSUE THREAD

**Issue by HectorAuvinen** [tqzhong/CG4MCTG#4]
Hi!

Thanks for uploading the scripts for Contrastive Prefix & CTRL!

The script is referencing a dataset class `GenDataset` from `dataset_benchmark.load_dataset`. Could you either describe how this works or upload the module/package? Thank you!

**Comment by tqzhong** [comment]
Hi！

Thank you for your reminder. We have already added the load_dataset.py script. In fact, the functionality of the GenDataset class is similar to that of the get_train_dataset function.

**Comment by HectorAuvinen** [comment]
Hi!


Thanks! It seems like there is another missing module ```mcd_utils_test```. ```load_dataset.py``` tries to import ```from dataset_benchmark.mcd.mcd_utils_test import get_mcd_splits, get_fewshot_splits, get_div_splits``` but this module does not seem to exist. I think it is not used in the current configuration but I'm just wondering if it will be necessary.

**Comment by tqzhong** [comment]
Hi, you can find these module from [there](https://github.com/Zhaoyi-Li21/compmctg_protocols/tree/5e7c71dc9d2a5e9405310617c2296a7d59c2dd32)
