### ISSUE TITLE
Non-Joint-Training Baseline methods

### ISSUE THREAD

**Issue by HectorAuvinen** [tqzhong/CG4MCTG#6]
Hello,

Are you planning on releasing the training/inference scripts for any of the baseline categories other than Joint-Training based? Each category has interesting methods and it would be great to have the training pipelines for LLAMA-2, and the best methods from the remaining two categories (Decoding-Time based & Separate-Training based).

**Comment by tqzhong** [comment]
The other codes are currently not intended for commitment, as they are all open-source. As for the LLM (LLAMA), we have not carried out any training on LLAMA and all entries in this section are solely inferences conducted directly through in-context learning.

**Comment by HectorAuvinen** [comment]
Hello,


I see, thanks! Could you share the prompt you used with LLAMA? And did you do any post-processing of the output or just evaluated whatever the llm generated? I was unable to find these details in the paper.

Edit: I found the prompt in the paper, I overlooked it previously.
